version: '3.4'
services:
  caseus-bot:
    build:
      context: .
      network: host
    image: caseus
    environment:
      - RUST_LOG=trace
    secrets:
      - teloxide_token
    entrypoint: [ '/bin/bash', '-c', 'export TELOXIDE_TOKEN=$$(cat /run/secrets/teloxide_token) ; ./caseus-foratus-helveticus "-4053606257"' ]
    restart: always
    network_mode: "host"
    volumes:
      - ./dates:/dates

secrets:
  teloxide_token:
    file: ./teloxide_token.txt
